[workspace]
resolver = "2"
members = [
    # lib (public)
    "./disassembler",
    "./emulator",

    # lib (private)
    "./src/utils",

    # bin
    "./src/cli",
    "./src/tui",
]

[workspace.dependencies]
anyhow = "1.0.93"
thiserror = "2.0.3"
