[package]
name = "sb_emu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
sb_emu_ir = { path = "./crates/ir" }
sb_emu_state = { path = "./crates/state" }
sb_emu_exec = { path = "./crates/exec" }
