[package]
name = "sb_emu_ir"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
sb_emu_ir_macros = { path = "../ir_macros" }
sb_emu_state = {  path = "../state" }
