[package]
name = "sb_emulator_ui_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
bpaf = { version = "0.9.15", features = ["derive"] }
sb_asm = { package = "sb_assembler", git = "https://github.com/shinrabansyo/assembler", rev = "1f40c9597e8307595cc0b6b261e251570150ddb2" }
